name: local-llm

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017"
  ollama:
    image: ollama/ollama
    ports:
      - "11434"
    volumes:
      - "model_data:/root/.ollama/models"
  chat-ui:
    image: ghcr.io/huggingface/chat-ui
    environment:
      MONGODB_URL: mongodb://mongodb:27017
    env_file: "./.env.local"
    ports:
      - "3000"
volumes:
  model_data: