# https://taskfile.dev

version: '3'


tasks:
  up:
    desc: "Starts up the docker compose, downloads models, and opens the browser"
    cmds:
      - docker compose up -d
      - task: download:models
      - task: open

  down:
    desc: "Stops the services"
    cmds:
      - docker compose down

  down:clean:
    desc: "Stops services and removes all caches"
    cmds:
      - docker compose down -v
  
  open:
    desc: "Finds the chat-ui and opens a browser pointed at the correct port. If multiple exist it uses the first one"
    cmds:
      - |
        port=$(docker compose port chat-ui 3000 | sed 's/0.0.0.0/localhost/')
        open http://${port}
  
  download:models:
    desc: "Run this once you start the docker compose to download the various models."
    cmds:
      - docker compose exec ollama ollama pull all-minilm
      - docker compose exec ollama ollama pull tinyllama
      - docker compose exec ollama ollama pull mistral

  hydrate:wiki:
    desc: "Hydrates the database using the huggingface wiki example data set"
    cmds:
      - |
        port=$(docker compose port postgresdb 5432 | sed 's/0.0.0.0://')
        echo "Connecting to psql via localhost on port ${port}"
        PGPASSWORD=postgres psql -h localhost -U postgres -p ${port} -d postgres -f hydrate.sql
